/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_usbfacedetect_main_USBCameraUtil */

#ifndef _Included_cn_usbfacedetect_main_USBCameraUtil
#define _Included_cn_usbfacedetect_main_USBCameraUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:    cn_usbfacedetect_main_USBCameraUtil
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_open(JNIEnv *env, jclass obj, jint devid);

JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_open2(JNIEnv *env, jclass obj, jbyteArray devId);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    init
 * Signature: (IIII)I
 */

JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_init(JNIEnv *env, jclass obj, jint width,
                                                    jint height, jint numbuf);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    streamon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_streamon(JNIEnv *env, jclass obj);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    yuvtorgb
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_webcamera_CameraUtil_yuvtorgb
        (JNIEnv *, jclass, jbyteArray, jbyteArray);


JNIEXPORT void JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_pixeltobmp(JNIEnv *env, jobject thiz,
                                                          jobject bitmap);


/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    dqbuf
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_cn_usbfacedetect_main_USBCameraUtil_dqbuf(JNIEnv *env, jclass obj,
                                                                            const jbyteArray videodata);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    qbuf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_qbuf(JNIEnv *env, jclass obj, jint index);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    streamoff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_streamoff(JNIEnv *env, jclass obj, jint index);

/*
 * Class:     cn_usbfacedetect_main_USBCameraUtil
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_release(JNIEnv *env, jclass obj);

JNIEXPORT void JNICALL
Java_cn_usbfacedetect_main_USBCameraUtil_yuvtorgb2(JNIEnv *env, jclass obj,
                                                         const jbyteArray yuvdata,
                                                         jintArray rgbdata);

#ifdef __cplusplus
}
#endif
#endif
